server-mode: grpc-gateway
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-caller: false
  # 是否禁止在 panic 及以上级别打印堆栈信息
  disable-stacktrace: false
  # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  # 生产环境建议设置为 info
  level: debug
  # 指定日志显示格式，可选值：console, json
  # 生产环境建议设置为 json
  format: json
  # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出
  output-paths: [/tmp/wishlight.log, stdout]
grpc:
    # GRPC 服务监听地址
  addr: 127.0.0.1:6666
# HTTP 服务器相关配置
http:
  # HTTP 服务器监听地址
  addr: 127.0.0.1:5555
# MySQL 数据库相关配置
mysql:
  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  addr: 127.0.0.1:3307
  # MySQL 用户名(建议授权最小权限集)
  username: wishlight
  # MySQL 用户密码
  password: wishlight1234
  # wishlight 系统所用的数据库名
  database: wishlight
  # MySQL 最大空闲连接数，默认 100
  max-idle-connections: 100
  # MySQL 最大打开的连接数，默认 100
  max-open-connections: 100
  # 空闲连接最大存活时间，默认 10s
  max-connection-life-time: 10s
  # GORM 日志级别, 1: silent, 2:error, 3:warn, 4:info
  # 生产环境建议设置为 4
  log-level: 4
# 安全服务器相关配置
tls:
  # 是否启动 HTTPS 安全服务器
  # 生产环境建议开启 HTTPS。并使用 HTTPS 协议访问 API 接口
  use-tls: false
  # 证书
  cert: /root/.wishlight/cert/server.crt
  # 证书 Key 文件
  key: /root/.wishlight/cert/server.key