// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MineHub_Healthz_FullMethodName = "/v1.MineHub/Healthz"
)

// MineHubClient is the client API for MineHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MineHubClient interface {
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type mineHubClient struct {
	cc grpc.ClientConnInterface
}

func NewMineHubClient(cc grpc.ClientConnInterface) MineHubClient {
	return &mineHubClient{cc}
}

func (c *mineHubClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, MineHub_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MineHubServer is the server API for MineHub service.
// All implementations must embed UnimplementedMineHubServer
// for forward compatibility.
type MineHubServer interface {
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	mustEmbedUnimplementedMineHubServer()
}

// UnimplementedMineHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMineHubServer struct{}

func (UnimplementedMineHubServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedMineHubServer) mustEmbedUnimplementedMineHubServer() {}
func (UnimplementedMineHubServer) testEmbeddedByValue()                 {}

// UnsafeMineHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MineHubServer will
// result in compilation errors.
type UnsafeMineHubServer interface {
	mustEmbedUnimplementedMineHubServer()
}

func RegisterMineHubServer(s grpc.ServiceRegistrar, srv MineHubServer) {
	// If the following call pancis, it indicates UnimplementedMineHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MineHub_ServiceDesc, srv)
}

func _MineHub_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MineHubServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MineHub_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MineHubServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MineHub_ServiceDesc is the grpc.ServiceDesc for MineHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MineHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MineHub",
	HandlerType: (*MineHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _MineHub_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/v1/apiserver.proto",
}
